# Forge mod metadata for Masta Essentials
modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1+
license="MIT"

[[mods]]
modId="mastaessentials"
version="1.0.0"
displayName="Masta Essentials"
description="A Minecraft mod that allows more homes and other utilities."
authors="Masta2222"

# Dependencies for the mod
[[dependencies.mastaessentials]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mastaessentials]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mastaessentials]]
modId="ftbessentials"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
